platform :ios,   '5.0'
pod 'AFNetworking',  '1.3.1'   
pod 'AFDownloadRequestOperation',   '0.0.1'
#pod 'MagicalRecord',   '2.0.8'
pod 'OCMock',         '>=2.0.1'
pod 'OCHamcrest',     '>=1.8'
pod 'UIKitCategoryAdditions_kang'
pod 'GPUImage'
