platform :ios,   '5.0'
#pod 'JSONKit',       '1.4'
pod 'AFNetworking',  '>=1.1.0'   
pod 'AFDownloadRequestOperation',   '0.0.1'
#pod 'MagicalRecord',   '2.0.8'
pod 'OCMock',         '>=2.0.1'
pod 'OCHamcrest',     '>=1.8'
pod 'UIKitCategoryAdditions_kang'
pod 'GPUImage'
